### ISSUE TITLE
kleiner is a smartass

### ISSUE THREAD

**Issue by Swim-Swim-Hungry** [Imakesoftware2/jbmod-spawnmenu#1]
kleiner is such a smartass that he is the only one that can be compiled and the icons aren't smartasses either because they can't be batched!!!!!!

**Comment by Swim-Swim-Hungry** [comment]
instructions unclear, issue still exists

**Comment by Imakesoftware2** [comment]
can you make it exactly clear what you mean exactly wdym it doesn't work with batching. is there an error that appears or something else.

**Comment by Swim-Swim-Hungry** [comment]
when i click the thumbnail_batch.py it doesn't do shit

**Comment by Imakesoftware2** [comment]
ok now it can ran without arguments

**Comment by Swim-Swim-Hungry** [comment]
> ok now it can ran without arguments

still doesn't do shit and kleiner is still the only one being compiled

**Comment by Imakesoftware2** [comment]
show me your items folder

**Comment by Swim-Swim-Hungry** [comment]
> show me your items folder

i'll record a video

**Comment by Swim-Swim-Hungry** [comment]
https://user-images.githubusercontent.com/117381694/226130001-17895685-b713-456e-8ea4-fcfd6686f7c0.mp4

**Comment by Imakesoftware2** [comment]
ok fetch the latest version

**Comment by Imakesoftware2** [comment]
and run this in the folder

**Comment by Imakesoftware2** [comment]
`pip install -r requirements.txt`

**Comment by Swim-Swim-Hungry** [comment]
> `pip install -r requirements.txt`

got ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by Swim-Swim-Hungry** [comment]
in the same folder as readme.md

**Comment by Swim-Swim-Hungry** [comment]
with the latest version

**Comment by Imakesoftware2** [comment]
git being silly they're now there

**Comment by Swim-Swim-Hungry** [comment]
error: subprocess-exited-with-error and error: legacy-install-failure while installing pillow

**Comment by Imakesoftware2** [comment]
> error: subprocess-exited-with-error and error: legacy-install-failure while installing pillow

what version of python are you using

**Comment by Swim-Swim-Hungry** [comment]
mingw64's python 3.10.9

**Comment by Imakesoftware2** [comment]
https://pillow.readthedocs.io/en/stable/installation.html

**Comment by Imakesoftware2** [comment]
Click on **Windows using MSYS2/MinGW**

**Comment by Swim-Swim-Hungry** [comment]
successfully installed

**Comment by Swim-Swim-Hungry** [comment]
successfully compiled

**Comment by Swim-Swim-Hungry** [comment]
now anybody won't have pain while compiling
